libtonc: DMA
DMA
Macros
#define DMA_TRANSFER(_dst, _src, count, ch, mode)
General purpose DMA transfer macro.
Functions
INLINE void dma_cpy (void *dst, const void *src, uint count, uint ch, u32 mode)
Generic DMA copy routine.
INLINE void dma_fill (void *dst, volatile u32 src, uint count, uint ch, u32 mode)
Generic DMA fill routine.
INLINE void dma3_cpy (void *dst, const void *src, uint size)
Specific DMA copier, using channel 3, word transfers.
INLINE void dma3_fill (void *dst, volatile u32 src, uint size)
Specific DMA filler, using channel 3, word transfers.
Detailed Description
Macro Definition Documentation
DMA_TRANSFER
#define DMA_TRANSFER (_dst, _src, count, ch, mode)
Value:
do {                                        \
    REG_DMA[ch].cnt= 0;                     \
    REG_DMA[ch].src= (const void*)(_src);   \
    REG_DMA[ch].dst= (void*)(_dst);         \
    REG_DMA[ch].cnt= (count) | (mode);      \
} while(0)
General purpose DMA transfer macro.
Parameters
_dst Destination address.
_src Source address.
count Number of transfers.
ch DMA channel.
mode DMA mode.
Function Documentation
dma3_cpy()
INLINE void dma3_cpy (void * dst, const void * src, uint size)
Specific DMA copier, using channel 3, word transfers.
Parameters
dst Destination address.
src Source address.
size Number of bytes to copy
Note
size is the number of bytes
References dma_cpy().
dma3_fill()
INLINE void dma3_fill (void * dst, volatile u32 src, uint size)
Specific DMA filler, using channel 3, word transfers.
Parameters
dst Destination address.
src Source value.
size Number of bytes to copy
Note
size is the number of bytes
References dma_fill().
dma_cpy()
INLINE void dma_cpy (void * dst, const void * src, uint count, uint ch, u32 mode)
Generic DMA copy routine.
Parameters
dst Destination address.
src Source address.
count Number of copies to perform.
ch DMA channel.
mode DMA transfer mode.
Note
count is the number of copies, not the size in bytes.
References REG_DMA.
Referenced by dma3_cpy().
dma_fill()
INLINE void dma_fill (void * dst, volatile u32 src, uint count, uint ch, u32 mode)
Generic DMA fill routine.
Parameters
dst Destination address.
src Source value.
count Number of copies to perform.
ch DMA channel.
mode DMA transfer mode.
Note
count is the number of copies, not the size in bytes.
References DMA_SRC_FIXED, and REG_DMA.
Referenced by dma3_fill().